DROP SCHEMA IF EXISTS  `employees`;

CREATE SCHEMA employees;

CREATE TABLE `employees`.`DEPARTMENT` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(30) NULL,
  `PHONE` VARCHAR(15) NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `employees`.`EMPLOYEE` (
  `ID` INT NOT NULL,
  `SURNAME` VARCHAR(20) NULL,
  `NAME` VARCHAR(10) NULL,
  `POSITION` VARCHAR(20) NULL,
  `DEPARTMENT_ID` INT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `employees`.`TASK` (
  `ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NULL,
  `EMPLOYEE_ID` INT NULL,
  PRIMARY KEY (`ID`));

ALTER TABLE `employees`.`EMPLOYEE`
ADD CONSTRAINT `fk_EMPLOYEE_1`
  FOREIGN KEY (`DEPARTMENT_ID`)
  REFERENCES `employees`.`DEPARTMENT` (`ID`)
  ON DELETE SET NULL
  ON UPDATE SET NULL;

ALTER TABLE `employees`.`TASK`
ADD CONSTRAINT `fk_TASK_1`
  FOREIGN KEY (`EMPLOYEE_ID`)
  REFERENCES `employees`.`EMPLOYEE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;